# Generated by Django 3.1.8 on 2023-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('acnumber', models.IntegerField()),
                ('ifsc', models.TextField(max_length=10)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
