# Generated by Django 3.1.8 on 2023-11-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='acnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='bankname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='ifsc',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='register',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
