# Generated by Django 3.1.8 on 2023-11-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_auto_20231104_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='acnumber',
            field=models.CharField(default='', max_length=100),
        ),
    ]
